version: '2'

services:
  nginx-proxy:
    container_name: nginx-proxy
    restart: always
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "WORKFOLDER/00_proxy/certs:/etc/nginx/certs:ro"
      - "WORKFOLDER/00_proxy/conf:/etc/nginx/conf.d"
      - "WORKFOLDER/00_proxy/vhost:/etc/nginx/vhost.d"
      - "WORKFOLDER/00_proxy/dhparam:/etc/nginx/dhparam"
      - "WORKFOLDER/00_proxy/html:/usr/share/nginx/html"
    networks:
      - net_proxy

  nginx-letsencrypt-companion:
    container_name: nginx-letsencrypt-companion
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "WORKFOLDER/00_proxy/certs:/etc/nginx/certs"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "nginx-proxy"
    networks:
      - net_proxy

networks:
  net_proxy:
    external:
      name: net_proxy
