version: '2'
                                                                                                                                                                                                                   
services:
                                                                                                                                                                                                                   
  nginx-proxy:
    container_name: nginx-proxy
    restart: always
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "WORKFOLDER/volumes/00_proxy_certs:/etc/nginx/certs:ro"
      - "WORKFOLDER/volumes/00_proxy_conf:/etc/nginx/conf.d"
      - "WORKFOLDER/volumes/00_proxy_vhost:/etc/nginx/vhost.d"
      - "WORKFOLDER/volumes/00_proxy_dhparam:/etc/nginx/dhparam"
      - "WORKFOLDER/volumes/00_proxy_html:/usr/share/nginx/html"
    networks:
      - net_proxy

  nginx-letsencrypt-companion:
    container_name: nginx-letsencrypt-companion
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "WORKFOLDER/volumes/00_proxy_certs:/etc/nginx/certs"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "nginx-proxy"
    networks:
      - net_proxy

networks:
  net_proxy:
    external:
      name: net_proxy
