version: '3'

services:
  spreedbackend:
    build:
      context: WORKFOLDER/nextcloud-spreed-signaling/docker/server/
      dockerfile: WORKFOLDER/nextcloud-spreed-signaling/docker/server/Dockerfile
    volumes:
      - "WORKFOLDER/server.conf:/config/server.conf"
    networks:
      - net_proxy
      - signal
#    network_mode: host
    restart: unless-stopped
#    expose:
#      - '80'
    depends_on:
      - nats
      - janus
      - coturn
      
  nats:
    image: nats:2.2.1
    volumes:
      - "WORKFOLDER/nextcloud-spreed-signaling/gnatsd.conf:/config/gnatsd.conf"
    command: ["-c", "/config/gnatsd.conf"]
    networks:
      - net_proxy
      - signal
    network_mode: host
    restart: unless-stopped
    
  janus:
    build: docker/janus
    command: ["janus", "--full-trickle"]
#    network_mode: host
    networks:
      - net_proxy
      - signal
    restart: unless-stopped
    
  coturn:
    build: docker/coturn
    networks:
      - net_proxy
      - signal
 #   network_mode: host
    environment:
      REALM: COTURN_DOMAIN
      STATIC_SECRET: SIGNALING_STATIC_SECRET
    restart: unless-stopped

networks:                                                                                                                                                                                                          
  net_proxy:                                                                                                                                                                                                       
    external:                                                                                                                                                                                                      
      name: net_proxy                                                                                                                                                                                              
  back_office:                                                                                                                                                                                                     
    driver: signal
