version: '3'

services:
  spreedbackend:
    build: .
    volumes:
      - "WORKFOLDER/config/server.conf:/config/server.conf"
    networks:
      - net_proxy
      - signal
#    network_mode: host
    restart: unless-stopped
    expose:
      - '80'
    depends_on:
      - nats
      - janus
      - coturn
      
  nats:
    image: nats:2.1
    volumes:
      - "WORKFOLDER/config/gnatsd.conf:/config/gnatsd.conf"
    command: ["-c", "/config/gnatsd.conf"]
    networks:
      - net_proxy
      - signal
#    network_mode: host
    restart: unless-stopped
    
  janus:
    build: docker/janus
    command: ["janus", "--full-trickle"]
#    network_mode: host
    networks:
      - net_proxy
      - signal
    restart: unless-stopped
    
  coturn:
    build: docker/coturn
    networks:
      - net_proxy
      - signal
#    network_mode: host
    environment:
      REALM: signaling.example.com
      STATIC_SECRET: openssl rand -hex 32
    restart: unless-stopped

networks:                                                                                                                                                                                                          
  net_proxy:                                                                                                                                                                                                       
    external:                                                                                                                                                                                                      
      name: net_proxy                                                                                                                                                                                              
  back_office:                                                                                                                                                                                                     
    driver: signal
